Added new prow job with feature gate turned off to run etcd-druid e2e tests with etcd-custom-image.
gardener/ci-infra pull request #1080
Opened 2024-01-04 04:43 UTC by ishan16696

/kind enhancement

**What this PR does / why we need it**:
The `UseEtcdWrapper` feature in etcd-druid is transitioning from alpha to beta stage, and will be set as the default option. in etcd-druid. Hence, `etcd-wrapper` will be used to run druid end-to-end (e2e) tests in pipeline.

However, we will continue to support etcd-custom-image(nondistroless-etcd). Therefore, the druid pipeline still requires to run druid e2e tests with etcd-custom-image.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/gardener/etcd-druid/issues/743

**Special notes for your reviewer**:
cc @aaronfern @shreyas-s-rao

2024-01-04 04:43 UTC, ishan16696 commented
/do-not-merge

2024-01-04 06:17 UTC, shreyas-s-rao requested changes

2024-01-04 06:17 UTC, shreyas-s-rao commented on config/jobs/etcd-druid/druid-e2e-kind-nondistroless-etcd.yaml
- Please change the descriptions on lines 16 and 51.
- Setting `USE_ETCD_DRUID_FEATURE_GATES` to false isn't enough. Additionally, the [etcd-druid skaffold profile](https://github.com/gardener/etcd-druid/blob/da484026874225f144410e512bb2073385a1fb2a/skaffold.yaml#L29-L37) needs to be adapted to have a new activation, ie `USE_ETCD_DRUID_FEATURE_GATES=false`. Since the default behavior will be to using the feature gate, this profile will need to be inverted to `do-not-use-feature-gates` and set `value.UseEtcdWrapper: false`.

You can make the changes in https://github.com/gardener/etcd-druid/pull/744

2024-01-04 12:12 UTC, ishan16696 commented on config/jobs/etcd-druid/druid-e2e-kind-nondistroless-etcd.yaml
done. PTAL

2024-01-06 07:54 UTC, shreyas-s-rao approved these changes
/lgtm

2024-01-06 08:16 UTC, ishan16696 commented
> /do-not-merge

This PR now can be merged.

2024-01-08 08:34 UTC, ishan16696 commented
/cc @oliver-goetz

2024-01-08 11:43 UTC, oliver-goetz commented
/approve

2024-01-08 11:46 UTC, merged