Add api diff job
gardener/ci-infra pull request #113
Opened 2022-03-08 13:03 UTC by acumino

/kind enhancement

**What this PR does / why we need it**:
This PR adds a new test job for the gardener/gardener to calculate the incompatible api changes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2022-03-11 10:58 UTC, timebertt requested changes

2022-03-11 10:58 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff-master.yaml
> +      - name: test-api-diff
```suggestion
      - name: test
```

2022-03-11 10:58 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff-master.yaml
> +    path_alias: gardener/gardener
Shouldn't be needed as our modules are identified via default pattern `github.com/org/repo`.

2022-03-11 10:58 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff-master.yaml
> +  - name: pull-gardener-apidiff-master
```suggestion
  - name: pull-gardener-apidiff
```

and rename the file to `gardener-apidiff.yaml`

2022-03-11 10:58 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff-master.yaml
> +        image: golang:1.17
```suggestion
        image: golang:1.17.7
```

2022-03-11 14:08 UTC, oliver-goetz commented
/hold
until https://github.com/gardener/gardener/pull/5532 is merged
apart from Tim's feedback no more remarks

2022-04-04 15:03 UTC, timebertt reviewed
Nit

2022-04-04 15:03 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff.yaml
> +    - ^master$ # run on master branch
Can you add the release branches?
```suggestion
    - ^master$
    - ^release-v\d+.\d+$
```

2022-04-04 18:04 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff.yaml
> +    - ^master$ # run on master branch
Right, I forgot about that.

2022-04-04 18:04 UTC, timebertt approved these changes
/lgtm

2022-04-04 18:09 UTC, merged

2022-04-04 18:13 UTC, timebertt commented on config/jobs/gardener/gardener-apidiff.yaml
> +        arge:
Noticed too late: 
```suggestion
        args:
```