Reactivate ghproxy token alerting
gardener/ci-infra pull request #136
Opened 2022-03-23 08:30 UTC by oliver-goetz

/kind bug

**What this PR does / why we need it**:
Bug in ghproxy token alerting has been [fixed in upstream](https://github.com/kubernetes/test-infra/pull/25702). Thus, we could enable it again.

**Which issue(s) this PR fixes**:
Fixes #133

**Special notes for your reviewer**:
Alerting was deactivated in [this PR](https://github.com/gardener/ci-infra/pull/80) before.

2022-03-24 18:44 UTC, timebertt requested changes
Can you also adapt the dashboard queries including this metric?

2022-03-24 18:44 UTC, timebertt commented on config/prow/cluster/monitoring/prow_prometheusrule.yaml
> +        github_token_usage{job="ghproxy", resource!="search"} <  1500
```suggestion
        github_token_usage{job="ghproxy", ratelimit_resource!="search"} <  1500
```

2022-03-24 18:44 UTC, timebertt commented on config/prow/cluster/monitoring/prow_prometheusrule.yaml
> +        predict_linear(github_token_usage{job="ghproxy", resource!="search"}[30m], 1 * 3600) < 0
```suggestion
        predict_linear(github_token_usage{job="ghproxy", ratelimit_resource!="search"}[30m], 1 * 3600) < 0
```

2022-03-24 18:44 UTC, timebertt commented on config/prow/cluster/monitoring/prow_prometheusrule.yaml
> +        predict_linear(github_token_usage{job="ghproxy", resource!="search"}[30m], 1 * 3600) < 0
```suggestion
        predict_linear(github_token_usage{job="ghproxy", ratelimit_resource!="search"}[30m], 1 * 3600) < 0
```
```suggestion
        predict_linear(github_token_usage{job="ghproxy", resource!="search"}[30m], 1 * 3600) < 0
```

2022-03-29 05:50 UTC, timebertt commented
> Can you also adapt the dashboard queries including this metric?

2022-03-29 07:03 UTC, oliver-goetz commented
oh I missed that 😅

2022-03-29 09:40 UTC, timebertt approved these changes
Thanks!

2022-03-29 09:41 UTC, merged