added prow jobs for dependency-watchdog
gardener/ci-infra pull request #435
Opened 2022-10-12 06:20 UTC by unmarshall

**What this PR does / why we need it**:
This PR adds prow jobs for unit tests and image builds of dependency-watchdog repository.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2022-10-12 06:29 UTC, rfranzke commented
@oliver-goetz Do we want/are we ready to let further repositories be managed via Prow? IIRC, last time we decided to only manage g/g and a few extensions until we have more maintainers. Is this still up-to-date?

2022-10-12 07:03 UTC, unmarshall commented
/invite @oliver-goetz

2022-10-12 08:33 UTC, oliver-goetz requested changes
There are some basic labels and plugins required for prow to work for a repository.
Please check what Dimitar did in `plugins.yaml`, `labels.yaml` and `ci-infra-periodics.yaml` for enabling `gardener-extension-shoot-oidc-service` see PR https://github.com/gardener/ci-infra/pull/157

2022-10-12 08:51 UTC, oliver-goetz commented
> @oliver-goetz Do we want/are we ready to let further repositories be managed via Prow? IIRC, last time we decided to only manage g/g and a few extensions until we have more maintainers. Is this still up-to-date?

There is only very maintenance effort for us when there are only a couple of prow jobs sharing the same pattern we use for gardener/gardener. That's the same setup as `gardener-extension-shoot-oidc-service` Dimitar added a while ago.

There will be more effort when other repositories would like to enable the full prow functionality including tide and other github integrations. For this we might need more maintainers. Maybe Dimitar, Madhav or other people from Bangalore team could help, when we come to this point.

2022-10-12 08:52 UTC, oliver-goetz commented
/kind enhancement

2022-10-14 07:00 UTC, oliver-goetz requested changes
There are too many labels and plugins for the "testing only" scenario in prow.

2022-10-14 07:10 UTC, unmarshall commented on config/prow/labels.yaml
> +  labels:
Ok what was not clear for me is what is maintained by gardener-robot and what will be maintained by prow. For now i will just use the labels that `gardener-extension-shoot-oidc-service` defined then.

2022-10-14 07:13 UTC, unmarshall commented on config/prow/plugins.yaml
> +    plugins:
Ok this is not clear. Wouldn't we still require `approve` or `assign` or `lgtm` etc.?

2022-10-14 07:21 UTC, unmarshall commented on config/prow/plugins.yaml
> +    plugins:
done

2022-10-14 07:22 UTC, unmarshall commented on config/prow/labels.yaml
> +  labels:
done

2022-10-14 07:24 UTC, oliver-goetz approved these changes
/lgtm

2022-10-14 07:24 UTC, merged