Add E2E Gardener upgrade test Prow jobs
gardener/ci-infra pull request #510
Opened 2022-12-01 08:23 UTC by seshachalam-yv

/kind enhancement
**What this PR does / why we need it**:
This PR adds new Prow jobs for Gardener upgrade tests. 
Gardener upgrade tests are introduce as part of this PR https://github.com/gardener/gardener/pull/7122
 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/2692 https://github.com/gardener/gardener/pull/7122

**Special notes for your reviewer**:

2022-12-01 08:34 UTC, seshachalam-yv commented
/hold until this PR https://github.com/gardener/gardener/pull/7122 merge

2022-12-01 09:11 UTC, oliver-goetz requested changes
Please harmonize the test names and the filenames accordingly.
The make targets and descriptions of single zone tests look wrong too.

2022-12-01 09:11 UTC, oliver-goetz commented on config/jobs/gardener/gardener-e2e-gardener-upgrade-kind-ha-single-zone.yaml
> +      description: Runs end-to-end tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments in pull requests
```suggestion
      description: Runs end-to-end Gardener upgrade tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments in pull requests
```

2022-12-01 09:11 UTC, oliver-goetz commented on config/jobs/gardener/gardener-e2e-gardener-upgrade-kind-ha-single-zone.yaml
> +    description: Runs end-to-end tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments periodically
```suggestion
    description: Runs end-to-end Gardener upgrade tests on a Seed with single zone with a Shoot with failure tolerance type 'node' for gardener developments periodically
```

2022-12-06 06:46 UTC, seshachalam-yv commented
> Please harmonize the test names and the filenames accordingly. The make targets and descriptions of single zone tests look wrong too.

Thanks for review @oliver-goetz 👍 
Adapted names based on new [g/g make targets](https://github.com/gardener/gardener/pull/7122/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R415-R421)

- `ci-e2e-kind-upgrade`
- `ci-e2e-kind-ha-single-zone-upgrade`
- `ci-e2e-kind-ha-multi-zone-upgrade`

2022-12-13 11:17 UTC, oliver-goetz approved these changes
/lgtm

2022-12-14 17:03 UTC, oliver-goetz reviewed
Found one more thing 🕵️‍♂️ 
Please make all jobs presubmit jobs optional.

/remove-lgtm

2022-12-14 19:20 UTC, oliver-goetz commented
/lgtm
/unhold https://github.com/gardener/gardener/pull/7122 is merged 🥳

2022-12-14 19:21 UTC, oliver-goetz commented
/unhold

2022-12-14 19:22 UTC, merged