Added new prow job to run e2e tests of etcd-druid with feature gates turned on
gardener/ci-infra pull request #798
Opened 2023-07-24 14:40 UTC by aaronfern

**What this PR does / why we need it**:
This PR introduces a new prow job `pull-etcd-druid-e2e-kind-alpha-features-true` that runs `etcd-druid` e2e tests with all feature gates turned on

**Which issue(s) this PR fixes**:
Fixes partially gardener/etcd-druid#643

**Special notes for your reviewer**:

2023-07-24 14:41 UTC, aaronfern commented
/hold
To be merged only after `etcd-druid:v0.19.0` has been releases.
I will notify here when the release has happened. In the meantime, PR review can proceed.

2023-07-25 14:42 UTC, oliver-goetz requested changes

2023-07-25 14:42 UTC, oliver-goetz commented on config/jobs/etcd-druid/druid-e2e-kind-alpha-features-true.yaml
> +        description: Runs KIND cluster based e2e tests for etcd druid developments in pull requests
```suggestion
        description: Runs KIND cluster based e2e tests for etcd druid developments in pull requests with activated alpha features
```

2023-07-26 05:50 UTC, aaronfern commented
Thanks for your review @oliver-goetz!
I've addressed your comments

2023-07-26 07:52 UTC, oliver-goetz approved these changes
/kind enhancement

/lgtm

2023-07-26 12:17 UTC, shreyas-s-rao approved these changes
/lgtm

2023-07-28 17:13 UTC, shreyas-s-rao commented
We need not wait until the etcd-druid release is made, since the prow job can run on PRs as soon as this [PR](https://github.com/gardener/etcd-druid/pull/646) is merged to master.

2023-07-31 09:45 UTC, aaronfern commented
This PR can now be merged as https://github.com/gardener/etcd-druid/pull/646 is ready to be merged and this prow job being enabled will be a good validator for merging the druid PR 
/unhold

2023-07-31 09:49 UTC, merged